### ISSUE TITLE
Type error: signingKey

### ISSUE THREAD

**Issue by microshine** [node-saml/xml-crypto#104]
`getKey` returns `Buffer`, but `getSignarure`, uses `signingKey` like string

``` javascript
this.getKey = function(keyInfo) {
    return fs.readFileSync(this.file);
}
```

[Source code](https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js#L26)

``` javascript
this.getSignature = function(signedInfo, signingKey) {
    var signer = crypto.createSign("RSA-SHA1")
    signer.update(signedInfo)
    var res = signer.sign(signingKey, 'base64')
    return res
}
```

[Source code](https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js#L88)

**Comment by yaronn** [comment]
nice catch. since signing is working there is probably some implicit conversion somewhere (I bet on signer.sign) but we should fix it for sure.

**Comment by cjbarth** [comment]
@microshine , please feel free to create a PR with a test suite to help address this issue.

**Comment by LoneRifle** [comment]
This issue will be triggered for Node versions before 11, the first version [accepting a Buffer](https://nodejs.org/docs/latest-v11.x/api/crypto.html#crypto_sign_sign_privatekey_outputencoding) as the private key argument for `Sign.sign()`. 

Versions 10 and before only accept String or Objects.

Given that version 14 is now our minimum supported version, we now have stronger guarantees that Buffer keys are accepted.
