### ISSUE TITLE
readme says enveloped-signature is supported but it doesn't work

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [node-saml/xml-crypto#109]
As per title, the code below works perfectly until you try to switch to enveloped-signature (commented line) and then it throws the following exception:

> TypeError: Not a string or buffer
>    at TypeError (native)
>    at Sign.Hash.update (crypto.js:70:16)
>    at RSASHA1.getSignature (/home/j/Documents/rockfish/node_modules/xml-crypto/lib/signed-xml.js:90:12)
>    at SignedXml.createSignature (/home/j/Documents/rockfish/node_modules/xml-crypto/lib/signed-xml.js:704:44)
>    at SignedXml.computeSignature (/home/j/Documents/rockfish/node_modules/xml-crypto/lib/signed-xml.js:495:29)
>    at Object.exports.test (/home/j/Documents/rockfish/lib/kg.js:45:9)
> ....etc....

```
  var pem = fs.readFileSync(global.appRoot + '/lib/testkey.pem');
    var key = pem.toString('ascii');
    var SignedXml = require('xml-crypto').SignedXml;

    var xml = "<library>" +
        "<book>" +
        "<name>Harry Potter</name>" +
        "</book>" +
        "</library>";

    var sig = new SignedXml();
//******************************************* BUG BUG BUG *****************************************
//Uncomment following line to see error
    //sig.canonicalizationAlgorithm='http://www.w3.org/2000/09/xmldsig#enveloped-signature';
//****************************************** /BUG *********************************************************
    sig.signingKey = pem;

    sig.computeSignature(xml);
    return sig.getSignedXml();
```

**Comment by WhatFreshHellIsThis** [comment]
Maybe related to me using the npm installed package which I now realize may be waaaaay out of date?

**Comment by WhatFreshHellIsThis** [comment]
Looks like a bug here:

```
EnvelopedSignature.prototype.process = function (node) {
  var signature = xpath(node, ".//*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0];  
  if (signature) signature.parentNode.removeChild(signature);
  return node;//<<----BUG?  Next function requires a string or buffer but this returns node
};

```

I modified that return to be return node.toString() and it works however the generated signed document is questionable as it's missing some elements I think so perhaps this algorithm isn't fully fleshed out yet?

**Comment by markstos** [comment]
I tried this fix for a case I thought was the same, bit it didn't work. Instead, I got a different error:

"TypeError: Cannot read property 'length' of undefined".

Do you have a complete example an XML file that uses enveloped signature to demonstrate that the fix works as expected?

**Comment by tulsirampalavalasa** [comment]
Hi ,

I am also facing the same issue " [TypeError: Not a buffer]" .Can  you please help me out in solving this


Thanks in advance

**Comment by BinniZenobioCordovaLeandro** [comment]
### **Hi have this error**
`TypeError: Cannot read property 'length' of undefined
    at Object.findChilds (C:\xampp\htdocs\soap-server\node_modules\xml-crypto\lib\utils.js:23:39)
    at ExclusiveCanonicalizationWithComments.ExclusiveCanonicalization.process (C:\xampp\htdocs\soap-server\node_modules\xml-crypto\lib\exclusive-canonicalization.js:208:40)
    at SignedXml.getCanonXml (C:\xampp\htdocs\soap-server\node_modules\xml-crypto\lib\signed-xml.js:829:26)
    at SignedXml.getCanonReferenceXml (C:\xampp\htdocs\soap-server\node_modules\xml-crypto\lib\signed-xml.js:401:15)
    at SignedXml.validateReferences (C:\xampp\htdocs\soap-server\node_modules\xml-crypto\lib\signed-xml.js:480:25)
    at SignedXml.checkSignature (C:\xampp\htdocs\soap-server\node_modules\xml-crypto\lib\signed-xml.js:352:13)
    at Object.<anonymous> (C:\xampp\htdocs\soap-server\tests\xmlCryptoVerifying.js:92:15)
    at Module._compile (internal/modules/cjs/loader.js:773:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)`

**### _when use the xml :_** 
`<?xml version="1.0" encoding="UTF-8"?>
<ar:ApplicationResponse xmlns:ar="urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><ext:UBLExtensions><ext:UBLExtension><ext:ExtensionContent><Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
  <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#WithComments"/>
  <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"/>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
      <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#WithComments"/>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    <DigestValue>mMnGeiz7wpEqV2HsJp66GAaSUZU=</DigestValue>
  </Reference>
</SignedInfo>
    <SignatureValue>nr7ReMrYgBckgivzowR8Dbk0AseiY0gjlsSn4Zx4q5qgenxitwW8kwju8mxg9ImRYK5Wkn6PR2ncIEy8Y0uaUJY86lNn8G8k13J4oiuVldo0u2c92NXWu8xUGys2fGZLoTv3tRpOV04Ofs8PADZACaIytK8y6/rzuHcPbuak+M80AuIrTErFdOS7P9TQVreIeU0Sng25s4ww/tOc30/4cqOg097sUqfAgFwIBrF8XkXinOZCqHTy+W/Y7W+LUphHv93e0hWYfbirxUbkkH1az8nKsXBhT22WFDcfGwDTilWm566zxVv9b6CbPhbDPf6zYqrPOBogIsbfUtJtljQtxg==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIGHzCCBQegAwIBAgIQCn/1lFmk8hWq/mp/VgjR4DANBgkqhkiG9w0BAQsFADBeMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMR0wGwYDVQQDExRHZW9UcnVzdCBSU0EgQ0EgMjAxODAeFw0xODAzMDgwMDAwMDBaFw0xOTA1MjcxMjAwMDBaMIGAMQswCQYDVQQGEwJQRTENMAsGA1UEBxMETGltYTFJMEcGA1UEChNAU1VQRVJJTlRFTkRFTkNJQSBOQUNJT05BTCBERSBBRFVBTkFTIFkgQURNSU5JU1RSQUNJT04gVFJJQlVUQVJJQTEXMBUGA1UEAwwOKi5zdW5hdC5nb2IucGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCxS4Wsb8FrQu/OJ4dKYAb1834aD9+muPmW2SN3ccBKndVC3RrdJNGsUYYT8YwSnS8tKKgpAbd12wP3wA23ejle8q5WyKcM6cvX28jYzhtNlmrfQl+oyG3s7xVTtgkFI/sAFNPU6UkFO5FaLGwUXuGiamqq6WAxIEXQEoq68pbskB20D9WtfRnLQDk9JxCju9c/Vo7DCqwykRwDtGiacKrBqWKv3BTPX7udqJLv1BSsJBpNpoXdveNyI+b7SNqDKe6JE1Im+hF0MXckncUWuZHRZ3tMXOSM71zawnNqXvb8VZY+Dpsja/qg++WaHHOmcqH20/RMZ4aV1mZLy372LuXDAgMBAAGjggK0MIICsDAfBgNVHSMEGDAWgBSQWP+wnHWoUVR3se3yo0MWOJ5sxTAdBgNVHQ4EFgQUidCGuoZ6s0y4w4FdCfFWVmRq75YwJwYDVR0RBCAwHoIOKi5zdW5hdC5nb2IucGWCDHN1bmF0LmdvYi5wZTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMD4GA1UdHwQ3MDUwM6AxoC+GLWh0dHA6Ly9jZHAuZ2VvdHJ1c3QuY29tL0dlb1RydXN0UlNBQ0EyMDE4LmNybDBMBgNVHSAERTBDMDcGCWCGSAGG/WwBATAqMCgGCCsGAQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMAgGBmeBDAECAjB1BggrBgEFBQcBAQRpMGcwJgYIKwYBBQUHMAGGGmh0dHA6Ly9zdGF0dXMuZ2VvdHJ1c3QuY29tMD0GCCsGAQUFBzAChjFodHRwOi8vY2FjZXJ0cy5nZW90cnVzdC5jb20vR2VvVHJ1c3RSU0FDQTIwMTguY3J0MAkGA1UdEwQCMAAwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdgCkuQmQtBhYFIe7E6LMZ3AKPDWYBPkb37jjd80OyA3cEAAAAWIHQAakAAAEAwBHMEUCIC+il0J53dcXEFGsDwMhI0n/djsUscRQ2QiuyUBZTrpcAiEAlFJ/RexAtO6B0EWl06PsUZ2Wexk24ClMHVD3tMNwBVcAdgBvU3asMfAxGdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAWIHQAgnAAAEAwBHMEUCIB3FkDM+626FhvtEU1KZsg5KRXij8ol4zE2r/3Pt2OdIAiEAvTIO5UCucHkzALKlbsksEGSf4QGQIehTXiAGWKjlfqcwDQYJKoZIhvcNAQELBQADggEBAJ6cNP7WC8MLc/NtLfyZR846CagTbfuJGCqoqdrO1gALsH+WOeJGoTfs9U0GPpX7VY/9onBdHxGHbObxEoSNlzUveLMkeG9FNADeZ+xYdxJ1QDO7IQr6EMQpw7noW8eOGl796PRuwBsC9EDiCwyoCkP2vzDF+xapYxxH3yPT6sIqAingn8SHMjyxsXQu7pr6yPqOCF+UfuYkB2UoQ6jexoMtlIMblg9f3f8zCuvgUWkwAzd1KoiG9FtIN21GeC0noANtOZUrNm1OBfg1EFsdsFfIsQlnKzrwJEAUnGbiUoYIVnviOuanR8efdLNe+Ny9m0RRItzhyoaaWsB3WbIU1/U=</X509Certificate><X509IssuerSerial><X509IssuerName>CN=GeoTrust RSA CA 2018, OU=www.digicert.com, O=DigiCert Inc, C=US</X509IssuerName><X509SerialNumber>13956682602747601529145667586552812000</X509SerialNumber></X509IssuerSerial></X509Data></KeyInfo><Proposito>Cumple proposito</Proposito><Revocacion>Cumple revocacion</Revocacion><TSL>Cumple tsl</TSL><Expiracion>No ha expirado</Expiracion></Signature></ext:ExtensionContent></ext:UBLExtension></ext:UBLExtensions><cbc:UBLVersionID>2.0</cbc:UBLVersionID><cbc:CustomizationID>1.0</cbc:CustomizationID><cbc:ID>201903574520108</cbc:ID><cbc:IssueDate>2019-04-01</cbc:IssueDate><cbc:IssueTime>00:00:00</cbc:IssueTime><cbc:ResponseDate>2019-04-04</cbc:ResponseDate><cbc:ResponseTime>21:03:57</cbc:ResponseTime><cac:Signature><cbc:ID>SignSUNAT</cbc:ID><cac:SignatoryParty><cac:PartyIdentification><cbc:ID>20131312955</cbc:ID></cac:PartyIdentification><cac:PartyName><cbc:Name>SUNAT</cbc:Name></cac:PartyName></cac:SignatoryParty><cac:DigitalSignatureAttachment><cac:ExternalReference><cbc:URI>#SignSUNAT</cbc:URI></cac:ExternalReference></cac:DigitalSignatureAttachment></cac:Signature><cbc:Note>4292 - La Versi&#243;n del UBL 2.0 se aceptar&#225; solo hasta el 30 de junio de 2019. - UBL 2.0 esta deprecado</cbc:Note><cac:SenderParty><cac:PartyIdentification><cbc:ID>20131312955</cbc:ID></cac:PartyIdentification></cac:SenderParty><cac:ReceiverParty><cac:PartyIdentification><cbc:ID>20101920721</cbc:ID></cac:PartyIdentification></cac:ReceiverParty><cac:DocumentResponse><cac:Response><cbc:ReferenceID>F001-0000533</cbc:ReferenceID><cbc:ResponseCode>0</cbc:ResponseCode><cbc:Description>La Factura numero F001-0000533, ha sido aceptada</cbc:Description></cac:Response><cac:DocumentReference><cbc:ID>F001-0000533</cbc:ID></cac:DocumentReference><cac:RecipientParty><cac:PartyIdentification><cbc:ID>6-20493978447</cbc:ID></cac:PartyIdentification></cac:RecipientParty></cac:DocumentResponse></ar:ApplicationResponse>`
### **_and this is, my code :_** 
`var select = require('xml-crypto').xpath,
    dom = require('xmldom').DOMParser,
    SignedXml = require('xml-crypto').SignedXml,
    FileKeyInfo = require('xml-crypto').FileKeyInfo,
    xpath = require('xpath'),
    fs = require('fs');

function generateCertFile(stringCert, directory = resources + '/cert') {
    var cdrFormated = verifyFormatCert(stringCert);
    var file = directory + '/cert.' + Date.now() + '.pem';
    console.log(file);
    fs.writeFileSync(file, cdrFormated);
    return file;
}

function verifyFormatCert(cert = null) {
    var prefix = "";
    var postfix = "";
    var certString = cert;
    // verificando formato
    if (!(/BEGIN CERTIFICATE/.test(cert))) {
        console.info('* BEGIN CERTIFICATE does not exist into cert');
        prefix = '-----BEGIN CERTIFICATE-----\n';
    }
    if (!(/END CERTIFICATE/.test(cert))) {
        console.info('** END CERTIFICATE does not exist into cert');
        postfix = '-----END CERTIFICATE-----';
    }
    if (!(/\n/.test())) {
        console.info('*** \\n does not exist into cert');
        console.log(certString);
        certString = certString.match(/.{0,64}/g).join('\n');
    } else if (certString.match(/\n/g).length == 22) {
        console.log('hay 22');
    }
    return prefix + certString + postfix;
}

var xml = fs.readFileSync("C:/xampp/htdocs/soap-server/tests/result.xml").toString();
var doc = new dom().parseFromString(xml);

var stringCert = select(doc, "//*[local-name(.)='X509Certificate']")[0].textContent;
var signature = select(doc, "//*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0];
if (signature) {
    signature.parentNode.removeChild(signature);
}

var file = generateCertFile(stringCert, './tests');

var option = {
    // idAttribute : "",
    signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha512",
    canonicalizationAlgorithm: "http://www.w3.org/2001/10/xml-exc-c14n#WithComments",
    implicitTransforms: [
        "http://www.w3.org/2000/09/xmldsig#enveloped-signature",
        "http://www.w3.org/2001/10/xml-exc-c14n#WithComments"
    ]
}

var sig = new SignedXml(null, option);

sig.keyInfoProvider = new FileKeyInfo(file);
console.log(sig.keyInfoProvider.getKey());
console.log(sig.keyInfoProvider.getKeyInfo());

sig.loadSignature(signature);
var res = sig.checkSignature(xml);
if (!res) {
    console.log("sig.validationErrors : ");
    console.log(sig.validationErrors);
}
console.log(res);`

### **Anyone has how resolve this?**

**Comment by cjbarth** [comment]
It appears that there are several issues discussed in this thread and some cross-posting going on. I'm going to close this. If there is a specific issue that still needs attention, please feel free to open a new issue and reference a comment here that is applicable to your issue.
