### ISSUE TITLE
InclusiveNamespaces how to include inclusivenamespace

### ISSUE THREAD

**Issue by SSANSH** [node-saml/xml-crypto#138]
Hi, How I can generate transform definition like with InclusiveNamespaces.

   ```
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
      <InclusiveNamespaces xmlns="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="oas v1 v11"/>
    </ds:Transform>
```

I checked the function SignedXml.prototype.createReferences but I don't see the way to include this definition.

      res += "<" + prefix + "Transforms>"
      for (var t in ref.transforms) {
        if (!ref.transforms.hasOwnProperty(t)) continue;

        var trans = ref.transforms[t]
        var transform = this.findCanonicalizationAlgorithm(trans)
        res += "<" + prefix + "Transform Algorithm=\"" + transform.getAlgorithmName() + "\"/>";
      }

Can you explain how to do and if its doable?

Thanks.

**Comment by tngan** [comment]
https://github.com/yaronn/xml-crypto/issues/94

@SSANSH checkout this one and you could find out the workaround as well

**Comment by shunkica** [comment]
@SSANSH did you ever figure it out?

I am parsing the signed document back to a xml doc and then manually adding the InclusiveNamespaces to ds:CanonicalizationMethod and ds:Transform but this is a very hacky approach.
