### ISSUE TITLE
Windows Store Receipt doesn't validate

### ISSUE THREAD

**Issue by metamorphy** [node-saml/xml-crypto#14]
Hi,

Thanks for your library.  I'm in a rush and I'd really, really be grateful if you could help me get this working with your library.  I want to be able to take one of the XML objects from the Windows store sample code:

Copy and paste one of the 2 `<Receipt>...</Receipt>` objects from here
http://msdn.microsoft.com/en-us/library/windows/apps/jj649137.aspx

and validate it with the Microsoft store cert here:
https://lic.apps.microsoft.com/licensing/certificateserver/?cid=b809e47cd0110a4db043b3f73e83acd917fe1336

Problem #1:
SignedXml.validateReferences() isn't expecting:

``` xml
  <Reference URI="">
```

and is trying to reference a char that doesn't exist:

``` xml
ref.uri[0]
```

Problem #2:
If I try hack around that, it still doesn't work.  I think the problem is that SignedXml.getCanonXml() is applying all the transforms:

``` xml
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
```

but I don't see where is applying the overall canonicalization

``` xml
<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
```

which is a different algorithm.

I don't think I'm the only one who would love to be able to use node to work with the Windows store.  Getting this to work would be greatly appreciated!

**Comment by vbrajath** [comment]
Hi,
I am using xml-crypto in node.js to create Digital signature, i got this error "invalid signature: for uri  calculated digest is 1lyn8jGYvy7r4WtL5L401yB2rWE= but the xml to validate supplies digest 7Z8sKYj47RNxPcjPxywArQfmEmg=".can any one plz help ?
