### ISSUE TITLE
addreference err

### ISSUE THREAD

**Issue by JeanPaulCE** [node-saml/xml-crypto#180]
I need to sign an xml with a p12 and I managed to remove the pem but at the time of signing with the following code:
`	var sig = new SignedXml()`
`	sig.addReference("//*[local-name(.)='library']") `
`	sig.signingKey = pem("./key.p12","pasword");return pem`
`	sig.computeSignature(read("./fax.xml"));//read return the xml`
`	fs.writeFileSync("signed.xml", sig.getSignedXml())`
I get this:
 ` throw new Error('the following xpath cannot be signed because it was not found: ' + ref.xpath)`

` Error: the following xpath cannot be signed because it was not found: //*[local-name(.)='library']`

I do not know about cripography or signed so I do not understand what happens and what should I use in addReference to sign the file

**Comment by giryco** [comment]
Can you please show the xml you are trying to sign?

**Comment by cjbarth** [comment]
I'm closing this issue as it appears to be stale. If there is an update, feel free to reply to reopen it.
