### ISSUE TITLE
Exclusive Canonicalization nsCompare is not spec complaint and creates invalid digests

### ISSUE THREAD

**Issue by ddowhy** [node-saml/xml-crypto#25]
The namespace compare method in exclusive-canonicalization.js is not compliant with the  XML Canonicalization specs.  The bug in this code is causing the canonical XML to be ordered slightly differently and thus failing signature validation because the digest values are being hashed over malformed canonicalXML.
http://www.w3.org/TR/xml-exc-c14n/ which refers to the rules specified in http://www.ietf.org/rfc/rfc3076.txt .  

Specifically, the spec states:
"
- An element's namespace nodes are sorted lexicographically by
  local name (the default namespace node, if one exists, has no
  local name and is therefore lexicographically least).
- An element's attribute nodes are sorted lexicographically with
  namespace URI as the primary key and local name as the
  secondary key (an empty namespace URI is lexicographically
  least). "

For the namespace comparison, instead of sorting by just local name (per spec) the code does this instead:
var attr1 = a.prefix+a.namespaceURI;
var attr2 = b.prefix+b.namespaceURI;
if (attr1 == attr2) return 0;
return attr1.localeCompare(attr2);

For clarification, the 'prefix' here is actually the local name.  

But the code is incorrect because the namespaceURI should not be a part of the comparison.

What ends up happening is that if you have something like this:
xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"

by doing the namespace comparison of the localName appended with the namespaceURI this string comparison will compare 'samlpurn:oasis:names:tc:SAML:2.0:protocol' to 'samlurnoasis:names:tc:SAML:2.0:assertion' 
and the resulting canonicalXML will be incorrectly out of order.  

EXPECTED (correct) canonical XML:
<Response xmlns="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Destination....

ACTUAL (incorrect) canonicalXML as a result of the bad namespace comparison:
<Response xmlns="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Destination=....

Verification of the digest value will fail since it is performed on the incorrect canonicalXML.

The namespace comparison should sort based on just the localNames, here as 'saml' to 'samlp'. 

The following code snippet shows one way this can be corrected to be spec compliant:
ExclusiveCanonicalization.prototype.nsCompare = function(a,b) {
  var attr1 = a.prefix; // don't compare a.namespaceURI;
  var attr2 = b.prefix; // don't compare b.namespaceURI;
  if (attr1 == attr2) return 0;
  return attr1.localeCompare(attr2);
};

While you're in there, you might also want to double check the attribute comparison too to make sure that is spec compliant as well (at a glance I'm not sure if the attribute comparison is correct either because it doesn't look like it's using the namespaceURI as a primary key for sorting first , it looks like it may use the localName if present instead of namespaceURI).

**Comment by dfloresgonz** [comment]
how did you solve it? SignedXml.prototype.getCanonXml changes the order of my attributes
