### ISSUE TITLE
Possible to handle S/MIME with referenced CipherData?

### ISSUE THREAD

**Issue by QAnders** [node-saml/xml-crypto#253]
I am getting data according to the AS4 specification which is encrypted SOAP but in an S/MIME envelope with referenced CipherData in another MIME part.

Can that be handled by xml-crypto?

Thanks for your package, much appreciated!

**Comment by cjbarth** [comment]
I don't believe `xml-crypto` handles anything outside the actual XML documents. You'd have to extract the document yourself before passing it to `xml-crypto`. If I misunderstand your question, please reply and we'll reopen your issue.
