### ISSUE TITLE
Reference DigestValue and  SignedInfo SignatureValue

### ISSUE THREAD

**Issue by dbrab** [node-saml/xml-crypto#259]
Hi guys, first of all I would like to thank you for the work you have done to build this tool, I am trying to sign some documents, however I have problems when the summary of the reference URL is generated, unfortunately the entity where I need to send the documents does not have documentation in this regard.

**XML BASE**
```xml
<?xml version="1.0" encoding="utf-8"?>
  <SemillaModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <valor>KNthlAufp9LwXC3FmU1p2NcMOMKXhut0qq+Tjhfn1FL2abSxvr3m98tpkp+A6wzciqiRgzNA8m6HwbydbAePupf2itlvo+0OlLDVFGacmFLnP+9694AENSERjM48TcUIqVW7oXvVpqgjjKo9xGvYxw==</valor>
    <fecha>2022-10-04T13:51:12.0942715-04:00</fecha>
  </SemillaModel>

```
**XML RESULT**
```xml
<?xml version="1.0" encoding="utf-8"?>
<SemillaModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <valor>KNthlAufp9LwXC3FmU1p2NcMOMKXhut0qq+Tjhfn1FL2abSxvr3m98tpkp+A6wzciqiRgzNA8m6HwbydbAePupf2itlvo+0OlLDVFGacmFLnP+9694AENSERjM48TcUIqVW7oXvVpqgjjKo9xGvYxw==</valor>
  <fecha>2022-10-04T13:51:12.0942715-04:00</fecha>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
        <DigestValue>jrXIlDuc4Bta8qTeBmxSTEJqRL4IRkf6eIGNFbxmE+Y=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>ofQ7kCSXLrxiQZ1DzDPKTs4ZI2+YeyTZGNIyUHlBRfw4jGLeKYy8YBw1qOKS/BM9NyMHB8hH2Y8L0AVUBpVl1Jbbea1bZfeRqvsmUKEEeIJQSDEZ3zvChhWb5J+xNJF3G1Zm7XyDCBklXCamV4djwf5d/ZwtwZ+dDecQJokc4GsLyfp3Qz+gXhmRBAs64Bai+vMfP50fwrtX8+S+UqhYCOfDVBam6YgNsGbEsCragvkYroYyW3Qc6qbpqm0GFVyjB3iAir46vd9n0quoq1KzkeHq4DIWpiPnwNj11dpdsNPq/7JY2+iNumak9oaIG8yn/MGVQj2v0jEsVAjVnJb67w==</SignatureValue>
    <KeyInfo>
      <X509Data>
        <X509Certificate>......</X509Certificate>
      </X509Data>
    </KeyInfo>
  </Signature>
</SemillaModel>
```

The entity has a software where it gives the result in this way, I understand that by doing the same operations and applying the same algorithms, it should give me this result as long as the document has not been modified, however when signing with xml-crypto, it gives me a different result for hashes and digestvalue

```javascript
    console.log('Creando certificado Firmado');
    var sig = new SignedXml()
    sig.digestAlgorithm ="http://www.w3.org/2001/04/xmlenc#sha256";
    sig.signatureAlgorithm = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
    sig.keyInfoProvider = new keyProvider(public_key)
    sig.canonicalizationAlgorithm = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"
    
    sig.addReference(`/*`, ["http://www.w3.org/2000/09/xmldsig#enveloped-signature"], "http://www.w3.org/2001/04/xmlenc#sha256", "", "", "", true)
    
    sig.signingKey =signingKey;
    sig.computeSignature(xml)
    fs.writeFileSync(xml_sign, sig.getSignedXml())
    
    console.log('Certificado firmado guardado en',xml_sign);
```

**RESULT WITH xml-crypto**

```xml
<?xml version="1.0" encoding="utf-8"?>
  <SemillaModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <valor>KNthlAufp9LwXC3FmU1p2NcMOMKXhut0qq+Tjhfn1FL2abSxvr3m98tpkp+A6wzciqiRgzNA8m6HwbydbAePupf2itlvo+0OlLDVFGacmFLnP+9694AENSERjM48TcUIqVW7oXvVpqgjjKo9xGvYxw==</valor>
    <fecha>2022-10-04T13:51:12.0942715-04:00</fecha>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
  <SignedInfo>
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
  <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
  <Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
  </Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
  <DigestValue>BMBZVPKXYm5pHI06/1AEr5zodueiXoOQgLbHjlEwqLc=</DigestValue>
  </Reference>
  </SignedInfo><SignatureValue>OT0HezpWgEZQIfzVcsS77sxjA7KnUYLflTJqrKOSDiRdQxTaSqxcyeOZVPLhU1iyFWdUpsaZx+vYkkCbHtG1woGfurym3BNsLdafGpzhzY3uGIqehhx1v34EzrVkSh//mobg6Hpl1VBNXLEW/xW1SgXqh6cfuDzoBzGB0wIPQbB3jNQZMmsDg5jdpupTtR97N1Cx/yP9TPFaC5+a80Or0r+/vP3SQH3sd2IyHcHRc1HNZ7ifFDs5uwx/gwy3b6boYMVA72rfT0/w0T8Cts0iFdt1LtkRAtA4Xg22MVnH+HNmvQ9GIjXMcMbHLeAVJ3tdcdcC7wMRaZDgbzS1mJlAPw==</SignatureValue>
  <KeyInfo><X509Data><X509Certificate>....</X509Certificate>
  </X509Data></KeyInfo>
  </Signature></SemillaModel>
```

As you can see the digestvalue is **BMBZVPKXYm5pHI06/1AEr5zodueiXoOQgLbHjlEwqLc=** , but the result should be **jrXIlDuc4Bta8qTeBmxSTEJqRL4IRkf6eIGNFbxmE+Y=** 
and since the SignatureValue depends on the latter, I understand that this will also be different

Try to sign it with other tools in another language like .net and the digest value ends up being this **bE1UYd1MsS1yd5vsg/a+eErotsoUfhIOQ3ZHRnW3lj0=**

Another clarification when I sign using the tool, when validating I have noticed that if I only have one transform when validating it adds another one by default and they end up being 2 , this breaks the validation using signed-xml

```javascript
  signed-xml.js  // line 685
  if (transforms.length === 0 || transforms[transforms.length - 1] === "http://www.w3.org/2000/09/xmldsig#enveloped-signature") {
      transforms.push("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")
  }
```

My question is, why does the digest value vary, when I change between tools, if in the end they end up being the same algorithms

**Update1**
I have noticed that everything depends on the canonXml, since this variable is used to make the signature of the reference, when I validate, for some reason due to the default behavior, it ends up changing the order of my headers, which breaks the validation
Original
`  <SemillaModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">`
**validation when adding a transformation by default    signed-xml.js  // line 685 change  order**

`  <SemillaModel xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
`

**Comment by Mikescops** [comment]
Hello @dbrab ,

I stumbled upon the same and decided to spend some time investigating the issue as it is critical for node-saml and passport-saml projects.

Here are my findings, indeed the final `canonXML` that is hashed to compute the digest is wrong because it contains the signature it self!

So I dug a bit more into exactly what happened, and the `canonXML` that is based on the fullXML from the currentNode goes through the listed transformers (max 2 transformers).

The important transformer as you may guess is the `http://www.w3.org/2000/09/xmldsig#enveloped-signature` which basically tells that the signature is included in the signed node.

After logging some fields in the transformer here is what i found >>>

![image](https://user-images.githubusercontent.com/4266283/195719800-a04037bd-04f3-49a4-b8b4-deb58eecd16d.png)

Two strings that are strictly identical when printed but return falsy.

The answer is indeed hidden out there, **as always**, and the fix is the following :

```
.replace(/\r?\n/g, '')
```

Now if we compare the 2 strings without carriage return, boom it works like a charm!

I'll link the PR bugfix and hope it is merged soon :+1:

**Comment by dbrab** [comment]
hello friend check your change add or not that patch does not change the final result of the signature that I have however I notice something strange it is supposed that if the algorithms are the same and use the same standard everything should be fine, so change the tools (start session in another language or another library as long as it follows the standard), but it seems to give me a different summary here than if I used the native .net cryptographic tools or the Java libraries
.
It doesn't validate me either, because it adds a transform by default when validating and this changes the structure of my initial signed xml, the cannonxml.

So I'm between a rock and a hard place, I think I'm missing something, or does the entity I'm trying to send the certificates to have their own transformation implementation that doesn't follow the standard or does each lib use a different standard? , what do you think ?

**Comment by dbrab** [comment]
@Mikescops Currently the only way I have to sign xml is using my entity tool, but this does not allow me to automate the process, I hope that someone with more understanding in this can give me some clue, if it is my problem, that of the entity, each tool has its own implementation, etc.

**Comment by cjbarth** [comment]
How does your signature compare with one generated over at [SAML Tool](https://www.samltool.com/online_tools.php)? They have been my go-to reference for a long time when dealing with SAML and have never led me astray.

**Comment by Mikescops** [comment]
Ah sorry I misunderstood your initial thread, I thought you were validating the signature not building it 😅

**Comment by dbrab** [comment]
I have not used the SAML Tool, but I will take a look at it, I am building and validating the signature, only the problem I have is that I do not know if the algorithm they use is wrong, I am wrong or something strange is happening.

**Comment by cjbarth** [comment]
Closed due to inactivity. Feel free to reopen if the issue persists.
