### ISSUE TITLE
Namespace support for Signature?

### ISSUE THREAD

**Issue by jbrunken** [node-saml/xml-crypto#26]
Is there a way to specify the namespace for the signature?

For example:

``` xml
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
...
</ds:Signature>
```

Thank you for providing this package!

**Comment by bjrmatos** [comment]
@yaronn would you accept a pull request with this feature? i'm working with the XML-UBL specification and need to prefix the signature with "ds:"; would love to see this in the main module rather than in a custom implementation.

Cool module BTW!

**Comment by yaronn** [comment]
Hi @jbrunken . Yes, would be great to have a feature that allows to customize the signature namespace.
