### ISSUE TITLE
[ENHANCEMENT]: Remove files, folders not needed on the release

### ISSUE THREAD

**Issue by angeljqv** [node-saml/xml-crypto#332]
### Is your feature request related to a problem? Please describe...

Why are those folders and files in node_modules?
![image](https://github.com/node-saml/xml-crypto/assets/79208641/813d6520-7cdb-4cf5-9156-b9cba0263887)

### Describe teh solution you'd like...

remove them

### Describe the alternatives you've considered...

I have not considered any other alternative

**Comment by cjbarth** [comment]
Yes, that is a problem. For sure that will be corrected with the 4.0 release. If you are in a position to help get that fixed for the 3.x branch, a PR is welcome as we are soon to release 3.2.

**Comment by angeljqv** [comment]
I would be delighted for v3, but unfortunately I don't know how to do it, imagine what was done on the page https://www.npmjs.com/package/xml-crypto
