### ISSUE TITLE
Bug/Outdated README: unclear whether signatureAlgorithm required or not

### ISSUE THREAD

**Issue by Roman-Octavian** [node-saml/xml-crypto#431]
# Context

In README.md it is stated that `signatureAlgorithm` is **OPTIONAL**:

https://github.com/node-saml/xml-crypto/blob/7e2d5a598e51acb03c7288557caabf9e5c26ab58/README.md?plain=1#L60

But this does not correspond to actual usage:

![image](https://github.com/node-saml/xml-crypto/assets/74454371/da59bb38-b7ad-4732-88d7-87ea9869f473)

# Reproduction
This behavior started occurring after updating to latest version `xml-crypto: 5.0.0`, therefore:
1. Install `xml-crypto` version `5.0.0`
2. Try to sign XML document without specifying `signatureAlgorithm`
3. Get runtime error

# Environment
- xml-crypto version 5.0.0
- NodeJS version 20.10.0
- NextJS version 13.5.4
- Windows 11 Pro 22H2
- Firefox 120.0.1 (64-bit)

# Suggested solution
a. Update README to reflect changes from version 5.0.0

b. If  `signatureAlgorithm` is not supposed to be required, fix requirement bug introduced in version 5.0.0

**Comment by cjbarth** [comment]
We've removed all the defaults from `xml-crypto` for version 5 in order to cause consumers to select their secure setup. It is the README that needs to be updated and we welcome a PR to do so.

**Comment by Roman-Octavian** [comment]
> We've removed all the defaults from `xml-crypto` for version 5 in order to cause consumers to select their secure setup. It is the README that needs to be updated and we welcome a PR to do so.

In response to this comment I made PR #432 a while ago. Consider reviewing or closing the PR if the change is unneeded after all. I think I forgot to lint it initially, but it should be OK now in that regard hopefully.
