### ISSUE TITLE
Include InclusiveNamespaces in transform tag

### ISSUE THREAD

**Issue by cmartin81** [node-saml/xml-crypto#60]
Hi
I need to define a reference when signing my xml with a html tag called: InclusiveNamespaces.
Are there any solution for this?

This is what I need to have inside my reference tag:
<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
   <InclusiveNamespaces  xmlns="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="#default samlp saml ds xs xsi"/>
</Transform>

**Comment by yaronn** [comment]
Hi @cmartin81 

This is not supported yet but some of the infrustructure so it might not be complex to implement if you want to try. Check this part in signed-xml.js:

https://github.com/auth0/xml-crypto/blob/be60701831079964ca56dbbd87a263af689fa509/lib/signed-xml.js#L416

you need two changes:

1. the getCannonXml() method can get a third parameter with the namespaces you want in the PrefixList (see how to call it here https://github.com/auth0/xml-crypto/blob/be60701831079964ca56dbbd87a263af689fa509/lib/signed-xml.js#L246)

2. In the same place where you added the parameter, see how the "transform" xml tag is built. you need to add it the "InclusiveNamespaces" child tag as in your example (using simple string concat). 

You can try to do it hard coded with your required namespaces so it will be very fast to check if it works.

Thanks,
Yaron

**Comment by zygimantus** [comment]
So, InclusiveNamespaces are not supported yet?
