### ISSUE TITLE
Prepare for 1.0

### ISSUE THREAD

**Issue by bjrmatos** [node-saml/xml-crypto#66]
The plan (discussed [here](https://github.com/yaronn/xml-crypto/pull/59)):
- [ ] **[deprecate]** `sig.loadSignature` (at least from the public API). 
- [ ] **[new behaviour]** `checkSignature(String: xmlDocument, [String: externalSignatureXmlDocument])` will search and validate only the first signature found (a cool feature would be let the user to validate a specific signature, vía a XPath expression).
- [ ] **[new feature]** `checkAllSignatures(String: xmlDocument, [String: externalSignatureXmlDocument])` will validate all signatures found (by default it will search inside the document for all instances of <Signature /> and validate all instances accordingly. if externalSignatureXmlDocument is specified it will search inside the external document).
- [ ] bring it back the condition: `//*[local-name(.)='SignedInfo']/*[local-name(.)='Reference' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']` (removed [here](https://github.com/yaronn/xml-crypto/pull/59/files#diff-e74e56dcb44165bb3bdd306d48a1fb7aL318)) to ensure a well formed xml document.. it will be ok since we have all the information that we need (namespaces) in the xml document node.
- [ ] both checkSignature and checkAllSignatures **must support the externalSignatureXmlDocument param** for external signatures. 
- [ ] **[refactor]** adapt current tests
- [x] **[fix/improve]** travis build (seems like it is broken since some time ago)
- [ ] **[add]** [debug](https://github.com/visionmedia/debug) module for logging in development
- [ ] **[remove]** hacky workaround in [this](https://github.com/yaronn/xml-crypto/commit/5f2278bd8158d23c34a31a7fdaf2ab6719b3a611) [commits](https://github.com/yaronn/xml-crypto/commit/7d69a26542e9bffeaeb2ca59ade67541f66fb853) if more information is not provided [here](https://github.com/yaronn/xml-crypto/pull/82)

:tada: The user wont need to specify the signature manually, xml-crypto will do it and will support multiple signature validation. :tada:

**Comment by bjrmatos** [comment]
i will post here if i find more improvements

**Comment by bjrmatos** [comment]
added a task to improve travis build

**Comment by bjrmatos** [comment]
added a task to use [debug](https://github.com/visionmedia/debug) module for logging useful information in development

**Comment by bjrmatos** [comment]
fixed travis builds in fbb8dacb8e18c24a075cfcef8af4ac8ea38a58d0

**Comment by fcorneli** [comment]
Is it possible to tag each release properly?

**Comment by bjrmatos** [comment]
@fcorneli sure! I will do it :)

**Comment by bjrmatos** [comment]
@yaronn can you enable the Travis webhook again? would be great to have results of travis builds in PRs again :)

**Comment by yaronn** [comment]
where do I enable it? "build push" and "build pull requests" are already on
in the travis project. maybe its in the yml? or you can also create a
travis project with your name.

On Thu, Oct 15, 2015 at 7:33 AM, BJR Matos <notifications@github.com> wrote:

> @yaronn <https://github.com/yaronn> can you enable the Travis webhook
> again? would be great to have results of travis builds in PRs again :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/xml-crypto/issues/66#issuecomment-148278468>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by bjrmatos** [comment]
can you look at the repository settings and confirm that travis is there?

screenshot from another repository:

<img width="1079" alt="captura de pantalla 2015-10-17 a las 2 39 03 p m" src="https://cloud.githubusercontent.com/assets/4262050/10560862/2f506d8e-74dd-11e5-93d3-116b52ef9900.png">

**Comment by yaronn** [comment]
yes, it's there exactly as in the picture.

On Sat, Oct 17, 2015 at 10:42 PM, BJR Matos <notifications@github.com>
wrote:

> can you look at the repository settings and confirm that travis is there?
>
> screenshot from another repository:
>
> [image: captura de pantalla 2015-10-17 a las 2 39 03 p m]
> <https://cloud.githubusercontent.com/assets/4262050/10560862/2f506d8e-74dd-11e5-93d3-116b52ef9900.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yaronn/xml-crypto/issues/66#issuecomment-148947036>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by bjrmatos** [comment]
added a task to remove the code added [here](https://github.com/yaronn/xml-crypto/pull/82) if more info is not provided.

**Comment by LoneRifle** [comment]
Closed as stale, we're now at versions beyond 1.0.
