### ISSUE TITLE
keyInfoProvider.getKey should be async

### ISSUE THREAD

**Issue by dominykas** [node-saml/xml-crypto#69]
(I'm on a roll, I know, but it's a good roll, right?)

The example for `getKey` in the README is using `fs.readFileSync` which is nice and all when you can actually use a sync version of a function - what I'm facing right now is a DER encoded key and so far - I haven't found a nice way to convert it to PEM (or use as is in `crypto`) other than by calling `openssl -inform DER -outform PEM` and doing that synchronously is really not an option.

**Comment by dominykas** [comment]
Found a sync way to convert DER to PEM in node.js (not sure if it's best/shortest):
```
var forge = require("node-forge");
var derKey = forge.util.decode64(certs[0].childNodes[0].data);
var asnObj = forge.asn1.fromDer(derKey);
var asn1Cert = forge.pki.certificateFromAsn1(asnObj);
return forge.pki.certificateToPem(asn1Cert);
```

**Comment by bjrmatos** [comment]
what i actually do in my apps based on xml-crypto is convert all keys to PEM format, on application start read the files with `fs.readFile` and keep the values in a shared module, and finally pass the result (Buffer) to my custom key info provider, with this way i don't read the key file every time and the `keyInfoProvider.getKey` method will never block my program because it is only retrieving what i have read before.

**Comment by dominykas** [comment]
Oh, OK. I was thinking about preloading, except that I figured that you do have to read it out from `keyInfo` param - in my case, I do get an `<X509Certificate/>` (in base64 encoded DER) inside the `keyInfo`. There is a strong use case for both - CPU heavy ops and I/O inside this method, so async felt natural.

Anyways, this is not an issue for me anymore [for now], so feel free to close this, if you consider the async `getKey` unnecessary.

**Comment by bjrmatos** [comment]
Ok, now i understand your use case :) i agree that async must be the way to go, it just would require to make some other methods async too.. I will leave this open until we implement this (after the module's author agree with this too)

**Comment by cjbarth** [comment]
@bjrmatos @dominykas , we'd love to have a PR with a test suite that addresses these concerns. Feel free to open one and we'll discuss.

**Comment by LoneRifle** [comment]
No longer relevant: KeyInfoProviders have been removed from 4.x onwards, and will eventually be replaced by a new approach to retrieve keys, where responsibility for key retrieval is placed on the caller
