### ISSUE TITLE
working with Axis/WSS4J web services

### ISSUE THREAD

**Issue by tedx** [node-saml/xml-crypto#7]
I wanted to see if I can write node.js code to work with a Axis/WSS4J based web services that I maintain. I captured a request and started writing code to analyse it and familiarize myself with xml-crypto.

```
xml = fs.readFileSync('request.xml', 'ascii', function(err,data) {
            if(err) {
                console.log("Could not open file"+ err);
                process.exit(1);
            }
        });
var sig = new SignedXml();
sig.keyInfoProvider = new FileKeyInfo("service-consumer-20121016-public.pem");
var signature = select(this.doc, "//*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0];
console.log(signature.toString());
sig.loadSignature(signature.toString());
var res = sig.checkSignature(xml);
```

request.xml:

<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  soapenv:Header
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" soapenv:mustUnderstand="1">
      <wsu:Timestamp xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="Timestamp-87498914">
    wsu:Created2013-01-17T17:20:28.257Z/wsu:Created
    wsu:Expires2013-01-17T17:25:28.257Z/wsu:Expires
      /wsu:Timestamp
      <wsse:BinarySecurityToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="CertId-5762605">MIIDujCCAyOgAwIBAgIJAL4olIXwkZQOMA0GCSqGSIb3DQEBBQUAMIGEMQ0wCwYDVQQKEwRKQ0RYMQwwCgYDVQQLEwNkZXYxHDAaBgkqhkiG9w0BCQEWDWpjZHhAamNkeC5vcmcxEjAQBgNVBAcTCVNhbiBEaWVnbzELMAkGA1UECBMCQ0ExCzAJBgNVBAYTAlVTMRkwFwYDVQQDExBzZXJ2aWNlLWNvbnN1bWVyMB4XDTEyMTAxNjEyNDE1NloXDTIyMDcxNjEyNDE1NlowgYQxDTALBgNVBAoTBEpDRFgxDDAKBgNVBAsTA2RldjEcMBoGCSqGSIb3DQEJARYNamNkeEBqY2R4Lm9yZzESMBAGA1UEBxMJU2FuIERpZWdvMQswCQYDVQQIEwJDQTELMAkGA1UEBhMCVVMxGTAXBgNVBAMTEHNlcnZpY2UtY29uc3VtZXIwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBANT5xJoZbag0zGmFk8BSA7aJfkFUBBVw+NiHpm8yRROsRJyKAnbGb8R7Jkyh9pTXXVrcC++qF21ipERJ78UE5fuqgTZbXEqSRhtEW377PEVSP8P9pR4XSpyCYqGs0Z77JAX3EalQmNj1iulGiY9d/22XyZixr4s4K94A3+ru+FONAgMBAAGjggEwMIIBLDAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBRIB+IzcpVPbP7e4O62u+TxfDxEZzCBuQYDVR0jBIGxMIGugBRIB+IzcpVPbP7e4O62u+TxfDxEZ6GBiqSBhzCBhDENMAsGA1UEChMESkNEWDEMMAoGA1UECxMDZGV2MRwwGgYJKoZIhvcNAQkBFg1qY2R4QGpjZHgub3JnMRIwEAYDVQQHEwlTYW4gRGllZ28xCzAJBgNVBAgTAkNBMQswCQYDVQQGEwJVUzEZMBcGA1UEAxMQc2VydmljZS1jb25zdW1lcoIJAL4olIXwkZQOMDEGA1UdJQQqMCgGCCsGAQUFBwMCBggrBgEFBQcDBAYIKwYBBQUHAwMGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIE8DANBgkqhkiG9w0BAQUFAAOBgQCz5grHrjsd4NFP0sfQEa677uqukB9jj+8gNYD6HqQ7N6D1hWMg81V1Qg6jDTJzjRlXx8Z1pAkbepR2TiPCPhvEjxn5KMT53gNBce8I8pHGUTN4Xev5USW4K+4GJEwly5eXTBAey6Rp7DlpnIvCmr0Xk7qgJZK+lA7NKv5mJV0KLA==/wsse:BinarySecurityToken
      <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="Signature-791234579">
    ds:SignedInfo
      <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">/ds:CanonicalizationMethod
      <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1">/ds:SignatureMethod
      <ds:Reference URI="#id-2141355741">
        ds:Transforms
          <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">/ds:Transform
        /ds:Transforms
        <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1">/ds:DigestMethod
        ds:DigestValueeH8rMl07vI5vfO0jI+riK8x4scc=/ds:DigestValue
      /ds:Reference
    /ds:SignedInfo
    ds:SignatureValueF5vcOJgohQ4qFqOUtYwjOLu47Dtp7BLKqL6ESuOoZ0+/6YZ3kZuDI+/8PKKyzNpIY7ebqg/22qz7S02HbukfjG3VblyZx2qUmIdQJQbYDiqU/yNjoXK9AEH3AhGwpkIOrnh5LGRhedvW4Kd7TBEJF2QMJUalcvXgP3GZJqtxiGY=/ds:SignatureValue
    <ds:KeyInfo Id="KeyId-1060827029">
      <wsse:SecurityTokenReference xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="STRId-910639009">
        <wsse:Reference URI="#CertId-5762605" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3">/wsse:Reference
      /wsse:SecurityTokenReference
    /ds:KeyInfo
      /ds:Signature
    /wsse:Security
    <wsa:MessageID soapenv:mustUnderstand="0">uuid:302caa30-60ca-11e2-8fd5-db8b3dff3bdb/wsa:MessageID
    <wsa:To soapenv:mustUnderstand="0">https://172.168.1.101:8443/JWSSMsgService-1.0/services/JWSSMsg/wsa:To
    <wsa:Action soapenv:mustUnderstand="0">urn:JWSSMsgService/sendMessage/wsa:Action
    <wsa:From soapenv:mustUnderstand="0">
      wsa:Addresshttp://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous/wsa:Address
    /wsa:From
  /soapenv:Header
  <soapenv:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-2141355741">
    <message xmlns="urn:jwss.jcdx.org">
      <data>Wk5SIFVVVVVVDQ0KUCAwMTE2NTBaIEZFQiAxMQ0NCkZNIEpDRFhURVNUDQ0KVE8gSkNEWA0NCkJUDQ0KVU5DTEFTDQ0KTVNHSUQvSkNEWFRFU1QvR09MRC85MC9GRUINDQpDVEMvOTAvQzkwLU45MC8vLy8vVVMvOTAvLy8wMA0NClBPUy8wMTE2NTFaNC9GRUIvMDAwNk42LzAwMDAxRTEvT1RSDQ0KUklHL0dQMS9SQUlTRUQgMS0yLTMvQ1JVSVNFUi9NRktDR01GS0NHTS85OTk5OTkvOTBGVC9DSEsgUklHRklFTERTDQ0KQVJSL0xPUyBBTkdFTEVTL1VTLzA3MTY1OVo4L0FVRy8vDQ0KREVQL1NBTiBESUVHTyBQVC9VUy8wOTIyMzBaNi9BVUcvLw0NCkVOREFUL0RFQ0w6IFgxDQ0KQlQNDQoKCgoKCgpOTk5O</data>
      <dn xsi:nil="true"></dn>
      <signature xsi:nil="true"></signature>
    </message>
  /soapenv:Body
/soapenv:Envelope

When I run the code I get:
[ 'invalid signature: for uri #id-2141355741 calculated digest is sWJn06HNJ9p3TkWxVRWf/BNaqN4= but the xml to validate supplies digest eH8rMl07vI5vfO0jI+riK8x4scc=' ]

So I started looking at how the digest is calculated and that's led to canonicalization. I changed SignedXml to print the result of canonicalization which is:

<soapenv:Body xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-2141355741">
    <message xmlns="urn:jwss.jcdx.org">
      <data>Wk5SIFVVVVVVDQ0KUCAwMTE2NTBaIEZFQiAxMQ0NCkZNIEpDRFhURVNUDQ0KVE8gSkNEWA0NCkJUDQ0KVU5DTEFTDQ0KTVNHSUQvSkNEWFRFU1QvR09MRC85MC9GRUINDQpDVEMvOTAvQzkwLU45MC8vLy8vVVMvOTAvLy8wMA0NClBPUy8wMTE2NTFaNC9GRUIvMDAwNk42LzAwMDAxRTEvT1RSDQ0KUklHL0dQMS9SQUlTRUQgMS0yLTMvQ1JVSVNFUi9NRktDR01GS0NHTS85OTk5OTkvOTBGVC9DSEsgUklHRklFTERTDQ0KQVJSL0xPUyBBTkdFTEVTL1VTLzA3MTY1OVo4L0FVRy8vDQ0KREVQL1NBTiBESUVHTyBQVC9VUy8wOTIyMzBaNi9BVUcvLw0NCkVOREFUL0RFQ0w6IFgxDQ0KQlQNDQoKCgoKCgpOTk5O</data>
      <dn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"></dn>
      <signature xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"></signature>
    </message>
  /soapenv:Body

Then I wrote a small java app to see how that compared to the Axis/WSS4J version where I got:

```
 [java] <soapenv:Body wsu:Id="id-2141355741" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
 [java]     <message xmlns="urn:jwss.jcdx.org">
 [java]       <data>Wk5SIFVVVVVVDQ0KUCAwMTE2NTBaIEZFQiAxMQ0NCkZNIEpDRFhURVNUDQ0KVE8gSkNEWA0NCkJUDQ0KVU5DTEFTDQ0KTVNHSUQvSkNEWFRFU1QvR09MRC85MC9GRUINDQpDVEMvOTAvQzkwLU45MC8vLy8vVVMvOTAvLy8wMA0NClBPUy8wMTE2NTFaNC9GRUIvMDAwNk42LzAwMDAxRTEvT1RSDQ0KUklHL0dQMS9SQUlTRUQgMS0yLTMvQ1JVSVNFUi9NRktDR01GS0NHTS85OTk5OTkvOTBGVC9DSEsgUklHRklFTERTDQ0KQVJSL0xPUyBBTkdFTEVTL1VTLzA3MTY1OVo4L0FVRy8vDQ0KREVQL1NBTiBESUVHTyBQVC9VUy8wOTIyMzBaNi9BVUcvLw0NCkVOREFUL0RFQ0w6IFgxDQ0KQlQNDQoKCgoKCgpOTk5O</data>
 [java]       <dn xsi:nil="true"></dn>
 [java]       <signature xsi:nil="true"></signature>
 [java]     </message>
 [java]   </soapenv:Body>
```

ignore the [java] that is a by product of running from an ant script.

I'm curious as to why they are different. Which W3C spec did you follow for your implementation? Have you done any interoperability testing with other XML security implementations?

**Comment by diondavidson** [comment]
I have having the exact same issue as the OP. I can verify signatures from other platforms but not Axis/WSS4J, and I suspect the canonization process, or the default use of InclusiveNamespaces by WSS4J. Any help? 
`<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="SOAP-ENV"/></ds:CanonicalizationMethod>`
