### ISSUE TITLE
support XAdES

### ISSUE THREAD

**Issue by bjrmatos** [node-saml/xml-crypto#89]
related to #61 

reference: https://xadesnet.codeplex.com/

**Comment by rmhrisk** [comment]
This is also a good reference https://www.microsoft.com/france/openness/open-source/interoperabilite_xades.aspx

**Comment by rmhrisk** [comment]
We have built on this excellent library and have the foundation for XAdES here : https://www.npmjs.com/package/xadesjs

**Comment by LoneRifle** [comment]
Duplicate of #87

**Comment by GauriSpears** [comment]
So is there a way to add <Object><QualifyingProperties>... **after** KeyInfo? All I see is to add something **into** KeyInfo with keyInfoAttributes property.

**Comment by GauriSpears** [comment]
UPD: I overrode getKeyInfo to successfully add xades object definition after KeyInfo node. Thanks for xml-crypto! It's VERY customizable!
